/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fra


fun main() {
    val S = fra.module.Solution()
    val ans = S.majorityElement(intArrayOf(2,2,1,1,1,2,2))
    println(ans)
}
